name: Test CI/CD

on:
  push:
    branches:
      - main

jobs:
  catalog_service_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout catalog-service
        uses: actions/checkout@v2
        with:
          path: PR6/catalog-service

      - name: Setup Node.js for catalog-service
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for catalog-service
        run: npm install
        working-directory: PR6/catalog-service

      - name: Run tests for catalog-service
        run: npm test
        working-directory: PR6/catalog-service

  orders_service_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout orders-service
        uses: actions/checkout@v2
        with:
          path: PR6/orders-service

      - name: Setup Node.js for orders-service
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for orders-service
        run: npm install
        working-directory: PR6/orders-service

      - name: Run tests for orders-service
        run: npm test
        working-directory: PR6/orders-service
